### ISSUE TITLE
Integrate with Cosmos SDK v0.50

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/rosetta#18]
I think Rosetta should start integrating with v0.50 to be ready to be tagged when Cosmos SDK v0.50 is released.
- https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.0-beta.0

**Comment by bizk** [comment]
Changes on cosmos-sdk v0.50 are causing unexpected errrors on parts of the code that were already working before.
I'm investgating if this is a bug on cosmos-sdk side, or something about the usage of such module that needs to be reworked. 

The function error is on 
`func (t *Tx) GetSigners(cdc codec.Codec) ([][]byte, []protov2.Message, error) `
In particular over:
`xs, msgv2, err := cdc.GetMsgAnySigners(msg)`

The error states: `InterfaceRegistry requires a proper address codec implementation to do address conversion

Not sure if it is the c

**Comment by julienrbrt** [comment]
You probably need signing options:

https://github.com/cosmos/cosmos-sdk/blob/860ab2fa7229227b79f9815e3693df1efb8dbca6/simapp/app.go#L195-L203

**Comment by bizk** [comment]
Implemented the optionss, seems it doesn't like it, I will try to register the interface and see how it works
